### ISSUE TITLE
Suggested README improvements

### ISSUE THREAD

**Issue by TechnologyClassroom** [ovjanman/Seeded-Propagation#2]
* The README could use some pictures or gifs since this repo deals with art.
  * As a hack to unclutter the repo, you can upload media to issues (such as this one) and then link to them from the repo so that external sites do not need to be referenced.  The drawback to this method is that they cannot be deleted after being uploaded.
* Most of the descriptions and process text from the Reddit posts could be copied and pasted to the README to provide more insight for those that find this repo through GitHub.

This advice is separate from what I plan to send in a patch later.

**Comment by TechnologyClassroom** [comment]
Much improved!

Only thing I would suggest for the README now is to move the gif up from the bottom to one of the first 5 lines.

**Comment by ovjanman** [comment]
Agreed!
